export const NotificationType = {
    NEW_SUBSCRIBER_NOTIFICATION: "NEW_SUBSCRIBER_NOTIFICATION",
    NEW_CHAT_NOTIFICATION: "NEW_CHAT_NOTIFICATION",
    DELETED_GROUP_CHAT_NOTIFICATION: "DELETED_GROUP_CHAT_NOTIFICATION",
    DELETED_PRIVATE_CHAT_NOTIFICATION: "DELETED_PRIVATE_CHAT_NOTIFICATION",
    NEW_ADMIN_IN_CHAT_NOTIFICATION: "NEW_ADMIN_IN_CHAT_NOTIFICATION",
    DELETED_CHAT_MEMBER_NOTIFICATION: "DELETED_CHAT_MEMBER_NOTIFICATION",
    MEMBER_LEFT_CHAT_NOTIFICATION: "MEMBER_LEFT_CHAT_NOTIFICATION"
}